spring:
  application:
    name: spring-cloud-nacos-gateway-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.242:58848
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      routes:
        - id: nacos-gateway-provider
          uri: lb://spring-cloud-nacos-gateway-provider
          predicates:
           - Path=/nacos/**
          filters:
           - StripPrefix=1
server:
  port: 8888
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
